#!/bin/bash
# 🌍 TravelAI Website - Quick Start Guide

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  🌍 TravelAI Website Setup                     ║"
echo "║             Your Professional Travel Booking Site             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: Install Dependencies"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Command: pip install -r requirements.txt"
echo "This installs: Flask, Werkzeug"
echo ""

echo "💾 STEP 2: Initialize Database"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Command: python init_db.py"
echo "This creates the SQLite database with:"
echo "  • Users table (for authentication)"
echo "  • Destinations table (12 travel locations)"
echo ""

echo "🚀 STEP 3: Start the Server"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Command: python app.py"
echo "The server will start at: http://localhost:5000"
echo ""

echo "🌐 STEP 4: Open in Browser"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL: http://localhost:5000"
echo ""

echo "✨ FEATURES READY TO USE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ User Registration & Login"
echo "✓ Browse 12 Amazing Destinations"
echo "✓ Smart Recommendation System"
echo "✓ Budget-Based Filtering"
echo "✓ Beautiful Responsive Design"
echo "✓ Professional UI with Images"
echo ""

echo "🧪 TEST THE WEBSITE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Homepage: See featured destinations"
echo "2. Register: Create a new account"
echo "3. Login: Sign in with credentials"
echo "4. Destinations: Browse all 12 places"
echo "5. Recommendations: Filter by budget & type"
echo ""

echo "📊 DESTINATIONS INCLUDED:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Beach:  Goa, Kerala, Maldives"
echo "Mountain: Manali, Leh Ladakh, Rishikesh, Munnar, Ooty, Coorg"
echo "Culture: Jaipur, Tajmahal, Dubai"
echo ""

echo "🔧 PROJECT STRUCTURE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "app.py                 - Flask application"
echo "init_db.py            - Database setup script"
echo "database/travel.db    - SQLite database"
echo "database/schema.sql   - Database schema"
echo "templates/            - HTML files"
echo "static/style.css      - Styling"
echo "requirements.txt      - Dependencies"
echo ""

echo "🌟 YOUR WEBSITE IS READY!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Start with: python app.py"
echo "Then visit: http://localhost:5000"
echo ""
